import { Report } from '../types';

export const MOCK_REPORTS: Report[] = [
  {
    id: '1',
    tenantId: 'ribeirao-preto',
    userId: '1',
    title: 'Buraco no meio da via',
    category: 'Buraco',
    address: 'Av. Presidente Vargas, 1200 - Centro, Ribeirão Preto',
    coordinates: { lat: -21.1767, lon: -47.8208 },
    description: 'Buraco grande no meio da via, causando risco para veículos e pedestres.',
    status: 'Analisando',
    isAnonymous: false,
    photos: [],
    createdAt: '2025-04-10T08:30:00.000Z',
    updates: [
      {
        timestamp: '2025-04-11T10:00:00.000Z',
        status: 'Analisando',
        comment: 'Equipe de manutenção agendada para vistoria.',
      },
    ],
  },
  {
    id: '2',
    tenantId: 'ribeirao-preto',
    userId: '1',
    title: 'Poste apagado há mais de uma semana',
    category: 'Iluminação Pública',
    address: 'Rua Álvares Cabral, 450 - Jardim Sumaré, Ribeirão Preto',
    coordinates: { lat: -21.1923, lon: -47.8351 },
    description: 'Poste apagado há mais de uma semana. Rua escura à noite, gerando insegurança.',
    status: 'Pendente',
    isAnonymous: false,
    photos: [],
    createdAt: '2025-04-15T19:45:00.000Z',
    updates: [],
  },
  {
    id: '3',
    tenantId: 'ribeirao-preto',
    userId: '1',
    title: 'Descarte irregular de entulho',
    category: 'Lixo',
    address: 'Rua General Osório, 800 - Vila Tibério, Ribeirão Preto',
    coordinates: { lat: -21.1654, lon: -47.8129 },
    description: 'Descarte irregular de entulho e lixo doméstico na calçada.',
    status: 'Resolvido',
    isAnonymous: true,
    photos: [],
    createdAt: '2025-04-02T07:00:00.000Z',
    updates: [
      {
        timestamp: '2025-04-03T09:00:00.000Z',
        status: 'Analisando',
        comment: 'Solicitação de coleta registrada.',
      },
      {
        timestamp: '2025-04-05T14:30:00.000Z',
        status: 'Resolvido',
        comment: 'Local limpo pela equipe de limpeza urbana.',
      },
    ],
  },
  {
    id: '4',
    tenantId: 'ribeirao-preto',
    userId: '1',
    title: 'Vazamento na calçada',
    category: 'Vazamento de Água',
    address: 'Rua José Bonifácio, 320 - Centro, Ribeirão Preto',
    coordinates: { lat: -21.1802, lon: -47.819 },
    description: 'Vazamento na calçada há dois dias. Água desperdiçada e calçada alagada.',
    status: 'Analisando',
    isAnonymous: false,
    photos: [],
    createdAt: '2025-04-18T11:20:00.000Z',
    updates: [
      {
        timestamp: '2025-04-18T15:00:00.000Z',
        status: 'Analisando',
        comment: 'DAERP notificado para reparo.',
      },
    ],
  },
  {
    id: '5',
    tenantId: 'ribeirao-preto',
    userId: '1',
    title: 'Terreno com água parada e foco de dengue',
    category: 'Foco de Dengue',
    address: 'Rua Visconde de Inhaúma, 150 - Alto da Boa Vista, Ribeirão Preto',
    coordinates: { lat: -21.1589, lon: -47.8072 },
    description: 'Terreno abandonado com acúmulo de água parada em pneus e vasos.',
    status: 'Pendente',
    isAnonymous: true,
    photos: [],
    createdAt: '2025-04-20T09:10:00.000Z',
    updates: [],
  },
  {
    id: '6',
    tenantId: 'ribeirao-preto',
    userId: '1',
    title: 'Galhos invadindo a fiação elétrica',
    category: 'Poda de Árvore',
    address: 'Av. Independência, 2500 - Jardim América, Ribeirão Preto',
    coordinates: { lat: -21.1711, lon: -47.8445 },
    description: 'Galhos invadindo a fiação elétrica e bloqueando a calçada.',
    status: 'Pendente',
    isAnonymous: false,
    photos: [],
    createdAt: '2025-04-22T16:00:00.000Z',
    updates: [],
  },
  {
    id: '7',
    tenantId: 'ribeirao-preto',
    userId: '1',
    title: 'Placa de PARE derrubada',
    category: 'Sinalização',
    address: 'Av. Dom Pedro I, 1100 - Campos Elíseos, Ribeirão Preto',
    coordinates: { lat: -21.185, lon: -47.83 },
    description: 'Placa de PARE derrubada na esquina. Risco de acidentes.',
    status: 'Resolvido',
    isAnonymous: false,
    photos: [],
    createdAt: '2025-03-28T08:00:00.000Z',
    updates: [
      {
        timestamp: '2025-03-29T10:00:00.000Z',
        status: 'Analisando',
        comment: 'Equipe de sinalização verificando o local.',
      },
      {
        timestamp: '2025-04-01T13:00:00.000Z',
        status: 'Resolvido',
        comment: 'Placa reinstalada.',
      },
    ],
  },
  {
    id: '8',
    tenantId: 'ribeirao-preto',
    userId: '1',
    title: 'Calçada quebrada e irregular',
    category: 'Calçada Danificada',
    address: 'Rua Tibiriçá, 650 - Centro, Ribeirão Preto',
    coordinates: { lat: -21.178, lon: -47.8165 },
    description: 'Calçada com pedras soltas e desnível, oferecendo risco de queda.',
    status: 'Pendente',
    isAnonymous: false,
    photos: [],
    createdAt: '2025-04-25T10:00:00.000Z',
    updates: [],
  },
  {
    id: '9',
    tenantId: 'ribeirao-preto',
    userId: '1',
    title: 'Buraco na entrada do condomínio',
    category: 'Buraco',
    address: 'Rua Mariana Junqueira, 200 - Jardim Paulista, Ribeirão Preto',
    coordinates: { lat: -21.195, lon: -47.815 },
    description: 'Buraco profundo na entrada do condomínio. Vários veículos já danificaram os pneus.',
    status: 'Analisando',
    isAnonymous: false,
    photos: [],
    createdAt: '2025-04-28T14:00:00.000Z',
    updates: [
      {
        timestamp: '2025-04-29T09:00:00.000Z',
        status: 'Analisando',
        comment: 'Ordem de serviço emitida.',
      },
    ],
  },
  {
    id: '10',
    tenantId: 'ribeirao-preto',
    userId: '1',
    title: 'Lixo acumulado em terreno baldio',
    category: 'Lixo',
    address: 'Rua Florêncio de Abreu, 900 - Vila Seixas, Ribeirão Preto',
    coordinates: { lat: -21.175, lon: -47.805 },
    description: 'Lixo acumulado em terreno baldio há semanas, com mau cheiro e ratos.',
    status: 'Pendente',
    isAnonymous: true,
    photos: [],
    createdAt: '2025-05-01T08:00:00.000Z',
    updates: [],
  },
  {
    id: '11',
    tenantId: 'ribeirao-preto',
    userId: '1',
    title: 'Poste sem luz na praça',
    category: 'Iluminação Pública',
    address: 'Praça XV de Novembro - Centro, Ribeirão Preto',
    coordinates: { lat: -21.1795, lon: -47.8225 },
    description: 'Três postes sem iluminação na praça central. Local ficou perigoso à noite.',
    status: 'Resolvido',
    isAnonymous: false,
    photos: [],
    createdAt: '2025-03-15T20:00:00.000Z',
    updates: [
      {
        timestamp: '2025-03-16T08:00:00.000Z',
        status: 'Analisando',
        comment: 'Técnicos acionados.',
      },
      {
        timestamp: '2025-03-18T17:00:00.000Z',
        status: 'Resolvido',
        comment: 'Postes reparados e ligados.',
      },
    ],
  },
  {
    id: '12',
    tenantId: 'ribeirao-preto',
    userId: '1',
    title: 'Semáforo com defeito',
    category: 'Sinalização',
    address: 'Av. Nove de Julho com Rua Duque de Caxias - Centro, Ribeirão Preto',
    coordinates: { lat: -21.1815, lon: -47.8195 },
    description: 'Semáforo piscando em amarelo há três dias, causando congestionamento.',
    status: 'Analisando',
    isAnonymous: false,
    photos: [],
    createdAt: '2025-05-03T07:30:00.000Z',
    updates: [
      {
        timestamp: '2025-05-03T11:00:00.000Z',
        status: 'Analisando',
        comment: 'CET-RP notificada.',
      },
    ],
  },
  {
    id: '13',
    tenantId: 'ribeirao-preto',
    userId: '1',
    title: 'Vazamento de esgoto na rua',
    category: 'Vazamento de Água',
    address: 'Rua São Sebastião, 400 - Vila Tibério, Ribeirão Preto',
    coordinates: { lat: -21.167, lon: -47.818 },
    description: 'Esgoto transbordando para a rua há dois dias. Cheiro forte e risco sanitário.',
    status: 'Pendente',
    isAnonymous: false,
    photos: [],
    createdAt: '2025-05-05T09:00:00.000Z',
    updates: [],
  },
  {
    id: '14',
    tenantId: 'ribeirao-preto',
    userId: '1',
    title: 'Árvore caída bloqueando a rua',
    category: 'Poda de Árvore',
    address: 'Rua Lafaiete, 1300 - Jardim Sumaré, Ribeirão Preto',
    coordinates: { lat: -21.194, lon: -47.832 },
    description: 'Árvore caiu após tempestade e está bloqueando metade da rua.',
    status: 'Resolvido',
    isAnonymous: false,
    photos: [],
    createdAt: '2025-04-12T06:00:00.000Z',
    updates: [
      {
        timestamp: '2025-04-12T09:00:00.000Z',
        status: 'Analisando',
        comment: 'Equipe de manejo urbano a caminho.',
      },
      {
        timestamp: '2025-04-12T14:00:00.000Z',
        status: 'Resolvido',
        comment: 'Árvore removida e rua liberada.',
      },
    ],
  },
  {
    id: '15',
    tenantId: 'ribeirao-preto',
    userId: '1',
    title: 'Caixa d\'água com larvas de mosquito',
    category: 'Foco de Dengue',
    address: 'Rua Duque de Caxias, 780 - Campos Elíseos, Ribeirão Preto',
    coordinates: { lat: -21.186, lon: -47.827 },
    description: 'Caixa d\'água destampada em imóvel abandonado com larvas visíveis.',
    status: 'Analisando',
    isAnonymous: true,
    photos: [],
    createdAt: '2025-05-06T10:00:00.000Z',
    updates: [
      {
        timestamp: '2025-05-07T08:00:00.000Z',
        status: 'Analisando',
        comment: 'Vigilância sanitária acionada para vistoria.',
      },
    ],
  },
  {
    id: '16',
    tenantId: 'ribeirao-preto',
    userId: '1',
    title: 'Calçada tomada por mato',
    category: 'Calçada Danificada',
    address: 'Av. Costábile Romano, 3200 - Ribeirânia, Ribeirão Preto',
    coordinates: { lat: -21.205, lon: -47.835 },
    description: 'Calçada completamente tomada por mato e raízes levantando o piso.',
    status: 'Pendente',
    isAnonymous: false,
    photos: [],
    createdAt: '2025-05-07T15:00:00.000Z',
    updates: [],
  },
  {
    id: '17',
    tenantId: 'ribeirao-preto',
    userId: '1',
    title: 'Buraco após obra da CPFL',
    category: 'Buraco',
    address: 'Rua Joinville, 550 - Alto da Boa Vista, Ribeirão Preto',
    coordinates: { lat: -21.16, lon: -47.811 },
    description: 'Buraco aberto após obra da CPFL nunca foi fechado corretamente.',
    status: 'Pendente',
    isAnonymous: false,
    photos: [],
    createdAt: '2025-05-08T11:00:00.000Z',
    updates: [],
  },
  {
    id: '18',
    tenantId: 'ribeirao-preto',
    userId: '1',
    title: 'Lixo jogado em área de preservação',
    category: 'Lixo',
    address: 'Parque Curupira - Ribeirão Preto',
    coordinates: { lat: -21.155, lon: -47.825 },
    description: 'Lixo e entulho jogado ilegalmente na borda do parque.',
    status: 'Analisando',
    isAnonymous: true,
    photos: [],
    createdAt: '2025-05-02T07:00:00.000Z',
    updates: [
      {
        timestamp: '2025-05-04T10:00:00.000Z',
        status: 'Analisando',
        comment: 'Secretaria de Meio Ambiente notificada.',
      },
    ],
  },
  {
    id: '19',
    tenantId: 'ribeirao-preto',
    userId: '1',
    title: 'Faixa de pedestre apagada',
    category: 'Sinalização',
    address: 'Rua Bernardino de Campos, 1100 - Centro, Ribeirão Preto',
    coordinates: { lat: -21.1773, lon: -47.8242 },
    description: 'Faixa de pedestre completamente apagada, pedestres atravessam sem segurança.',
    status: 'Pendente',
    isAnonymous: false,
    photos: [],
    createdAt: '2025-05-09T09:00:00.000Z',
    updates: [],
  },
  {
    id: '20',
    tenantId: 'ribeirao-preto',
    userId: '1',
    title: 'Iluminação do parque com defeito',
    category: 'Iluminação Pública',
    address: 'Parque Prefeito Luís Roberto Jábali - Ribeirão Preto',
    coordinates: { lat: -21.2, lon: -47.795 },
    description: 'Metade das luminárias do parque estão apagadas, tornando o local inseguro.',
    status: 'Analisando',
    isAnonymous: false,
    photos: [],
    createdAt: '2025-05-08T19:00:00.000Z',
    updates: [
      {
        timestamp: '2025-05-09T08:00:00.000Z',
        status: 'Analisando',
        comment: 'Técnicos agendados para avaliação.',
      },
    ],
  },
];
